/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Proagricrowd extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1723566956;

	/**
	 * The reference instance of <code>proagricrowd</code>
	 */
	public static final Proagricrowd PROAGRICROWD = new Proagricrowd();

	/**
	 * No further instances allowed
	 */
	private Proagricrowd() {
		super("proagricrowd");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.webonise.proagricrowd.sql.tables.Addresses.ADDRESSES,
			com.webonise.proagricrowd.sql.tables.Databasechangelog.DATABASECHANGELOG,
			com.webonise.proagricrowd.sql.tables.Databasechangeloglock.DATABASECHANGELOGLOCK,
			com.webonise.proagricrowd.sql.tables.Events.EVENTS,
			com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS,
			com.webonise.proagricrowd.sql.tables.Users.USERS,
			com.webonise.proagricrowd.sql.tables.UsersType.USERS_TYPE);
	}
}
