/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql;

/**
 * Convenience access to all tables in proagricrowd
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table proagricrowd.DATABASECHANGELOG
	 */
	public static final com.webonise.proagricrowd.sql.tables.Databasechangelog DATABASECHANGELOG = com.webonise.proagricrowd.sql.tables.Databasechangelog.DATABASECHANGELOG;

	/**
	 * The table proagricrowd.DATABASECHANGELOGLOCK
	 */
	public static final com.webonise.proagricrowd.sql.tables.Databasechangeloglock DATABASECHANGELOGLOCK = com.webonise.proagricrowd.sql.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

	/**
	 * The table proagricrowd.EVENTS
	 */
	public static final com.webonise.proagricrowd.sql.tables.Events EVENTS = com.webonise.proagricrowd.sql.tables.Events.EVENTS;

	/**
	 * The table proagricrowd.INDIVIDUALS
	 */
	public static final com.webonise.proagricrowd.sql.tables.Individuals INDIVIDUALS = com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS;

	/**
	 * The table proagricrowd.SUCCESS_STORIES
	 */
	public static final com.webonise.proagricrowd.sql.tables.SuccessStories SUCCESS_STORIES = com.webonise.proagricrowd.sql.tables.SuccessStories.SUCCESS_STORIES;

	/**
	 * The table proagricrowd.USERS
	 */
	public static final com.webonise.proagricrowd.sql.tables.Users USERS = com.webonise.proagricrowd.sql.tables.Users.USERS;

	/**
	 * The table proagricrowd.USERS_TYPE
	 */
	public static final com.webonise.proagricrowd.sql.tables.UsersType USERS_TYPE = com.webonise.proagricrowd.sql.tables.UsersType.USERS_TYPE;
}
