/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Addresses implements java.io.Serializable {

	private static final long serialVersionUID = -732184564;

	private java.lang.Integer  addrId;
	private java.lang.String   addrLine1;
	private java.lang.String   addrLine2;
	private java.lang.String   addrArea;
	private java.lang.String   addrCity;
	private java.lang.String   addrState;
	private java.lang.String   addrCountry;
	private java.lang.Integer  addrPincode;
	private java.sql.Timestamp addrCreationDate;

	public Addresses() {}

	public Addresses(
		java.lang.Integer  addrId,
		java.lang.String   addrLine1,
		java.lang.String   addrLine2,
		java.lang.String   addrArea,
		java.lang.String   addrCity,
		java.lang.String   addrState,
		java.lang.String   addrCountry,
		java.lang.Integer  addrPincode,
		java.sql.Timestamp addrCreationDate
	) {
		this.addrId = addrId;
		this.addrLine1 = addrLine1;
		this.addrLine2 = addrLine2;
		this.addrArea = addrArea;
		this.addrCity = addrCity;
		this.addrState = addrState;
		this.addrCountry = addrCountry;
		this.addrPincode = addrPincode;
		this.addrCreationDate = addrCreationDate;
	}

	public java.lang.Integer getAddrId() {
		return this.addrId;
	}

	public void setAddrId(java.lang.Integer addrId) {
		this.addrId = addrId;
	}

	public java.lang.String getAddrLine1() {
		return this.addrLine1;
	}

	public void setAddrLine1(java.lang.String addrLine1) {
		this.addrLine1 = addrLine1;
	}

	public java.lang.String getAddrLine2() {
		return this.addrLine2;
	}

	public void setAddrLine2(java.lang.String addrLine2) {
		this.addrLine2 = addrLine2;
	}

	public java.lang.String getAddrArea() {
		return this.addrArea;
	}

	public void setAddrArea(java.lang.String addrArea) {
		this.addrArea = addrArea;
	}

	public java.lang.String getAddrCity() {
		return this.addrCity;
	}

	public void setAddrCity(java.lang.String addrCity) {
		this.addrCity = addrCity;
	}

	public java.lang.String getAddrState() {
		return this.addrState;
	}

	public void setAddrState(java.lang.String addrState) {
		this.addrState = addrState;
	}

	public java.lang.String getAddrCountry() {
		return this.addrCountry;
	}

	public void setAddrCountry(java.lang.String addrCountry) {
		this.addrCountry = addrCountry;
	}

	public java.lang.Integer getAddrPincode() {
		return this.addrPincode;
	}

	public void setAddrPincode(java.lang.Integer addrPincode) {
		this.addrPincode = addrPincode;
	}

	public java.sql.Timestamp getAddrCreationDate() {
		return this.addrCreationDate;
	}

	public void setAddrCreationDate(java.sql.Timestamp addrCreationDate) {
		this.addrCreationDate = addrCreationDate;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Addresses other = (Addresses) obj;
		if (addrId == null) {
			if (other.addrId != null)
				return false;
		}
		else if (!addrId.equals(other.addrId))
			return false;
		if (addrLine1 == null) {
			if (other.addrLine1 != null)
				return false;
		}
		else if (!addrLine1.equals(other.addrLine1))
			return false;
		if (addrLine2 == null) {
			if (other.addrLine2 != null)
				return false;
		}
		else if (!addrLine2.equals(other.addrLine2))
			return false;
		if (addrArea == null) {
			if (other.addrArea != null)
				return false;
		}
		else if (!addrArea.equals(other.addrArea))
			return false;
		if (addrCity == null) {
			if (other.addrCity != null)
				return false;
		}
		else if (!addrCity.equals(other.addrCity))
			return false;
		if (addrState == null) {
			if (other.addrState != null)
				return false;
		}
		else if (!addrState.equals(other.addrState))
			return false;
		if (addrCountry == null) {
			if (other.addrCountry != null)
				return false;
		}
		else if (!addrCountry.equals(other.addrCountry))
			return false;
		if (addrPincode == null) {
			if (other.addrPincode != null)
				return false;
		}
		else if (!addrPincode.equals(other.addrPincode))
			return false;
		if (addrCreationDate == null) {
			if (other.addrCreationDate != null)
				return false;
		}
		else if (!addrCreationDate.equals(other.addrCreationDate))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addrId == null) ? 0 : addrId.hashCode());
		result = prime * result + ((addrLine1 == null) ? 0 : addrLine1.hashCode());
		result = prime * result + ((addrLine2 == null) ? 0 : addrLine2.hashCode());
		result = prime * result + ((addrArea == null) ? 0 : addrArea.hashCode());
		result = prime * result + ((addrCity == null) ? 0 : addrCity.hashCode());
		result = prime * result + ((addrState == null) ? 0 : addrState.hashCode());
		result = prime * result + ((addrCountry == null) ? 0 : addrCountry.hashCode());
		result = prime * result + ((addrPincode == null) ? 0 : addrPincode.hashCode());
		result = prime * result + ((addrCreationDate == null) ? 0 : addrCreationDate.hashCode());
		return result;
	}
}
