/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Events implements java.io.Serializable {

	private static final long serialVersionUID = -1964447787;

	private java.lang.Integer  eventId;
	private java.lang.String   eventTitle;
	private java.lang.String   eventDesc;
	private java.lang.String   eventLocation;
	private java.lang.Integer  eventOrganiser;
	private java.lang.Integer  eventExpert;
	private java.lang.Integer  eventEstimatedCost;
	private java.sql.Timestamp eventDate;
	private java.sql.Timestamp eventCreationDate;

	public Events() {}

	public Events(
		java.lang.Integer  eventId,
		java.lang.String   eventTitle,
		java.lang.String   eventDesc,
		java.lang.String   eventLocation,
		java.lang.Integer  eventOrganiser,
		java.lang.Integer  eventExpert,
		java.lang.Integer  eventEstimatedCost,
		java.sql.Timestamp eventDate,
		java.sql.Timestamp eventCreationDate
	) {
		this.eventId = eventId;
		this.eventTitle = eventTitle;
		this.eventDesc = eventDesc;
		this.eventLocation = eventLocation;
		this.eventOrganiser = eventOrganiser;
		this.eventExpert = eventExpert;
		this.eventEstimatedCost = eventEstimatedCost;
		this.eventDate = eventDate;
		this.eventCreationDate = eventCreationDate;
	}

	public java.lang.Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(java.lang.Integer eventId) {
		this.eventId = eventId;
	}

	public java.lang.String getEventTitle() {
		return this.eventTitle;
	}

	public void setEventTitle(java.lang.String eventTitle) {
		this.eventTitle = eventTitle;
	}

	public java.lang.String getEventDesc() {
		return this.eventDesc;
	}

	public void setEventDesc(java.lang.String eventDesc) {
		this.eventDesc = eventDesc;
	}

	public java.lang.String getEventLocation() {
		return this.eventLocation;
	}

	public void setEventLocation(java.lang.String eventLocation) {
		this.eventLocation = eventLocation;
	}

	public java.lang.Integer getEventOrganiser() {
		return this.eventOrganiser;
	}

	public void setEventOrganiser(java.lang.Integer eventOrganiser) {
		this.eventOrganiser = eventOrganiser;
	}

	public java.lang.Integer getEventExpert() {
		return this.eventExpert;
	}

	public void setEventExpert(java.lang.Integer eventExpert) {
		this.eventExpert = eventExpert;
	}

	public java.lang.Integer getEventEstimatedCost() {
		return this.eventEstimatedCost;
	}

	public void setEventEstimatedCost(java.lang.Integer eventEstimatedCost) {
		this.eventEstimatedCost = eventEstimatedCost;
	}

	public java.sql.Timestamp getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(java.sql.Timestamp eventDate) {
		this.eventDate = eventDate;
	}

	public java.sql.Timestamp getEventCreationDate() {
		return this.eventCreationDate;
	}

	public void setEventCreationDate(java.sql.Timestamp eventCreationDate) {
		this.eventCreationDate = eventCreationDate;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Events other = (Events) obj;
		if (eventId == null) {
			if (other.eventId != null)
				return false;
		}
		else if (!eventId.equals(other.eventId))
			return false;
		if (eventTitle == null) {
			if (other.eventTitle != null)
				return false;
		}
		else if (!eventTitle.equals(other.eventTitle))
			return false;
		if (eventDesc == null) {
			if (other.eventDesc != null)
				return false;
		}
		else if (!eventDesc.equals(other.eventDesc))
			return false;
		if (eventLocation == null) {
			if (other.eventLocation != null)
				return false;
		}
		else if (!eventLocation.equals(other.eventLocation))
			return false;
		if (eventOrganiser == null) {
			if (other.eventOrganiser != null)
				return false;
		}
		else if (!eventOrganiser.equals(other.eventOrganiser))
			return false;
		if (eventExpert == null) {
			if (other.eventExpert != null)
				return false;
		}
		else if (!eventExpert.equals(other.eventExpert))
			return false;
		if (eventEstimatedCost == null) {
			if (other.eventEstimatedCost != null)
				return false;
		}
		else if (!eventEstimatedCost.equals(other.eventEstimatedCost))
			return false;
		if (eventDate == null) {
			if (other.eventDate != null)
				return false;
		}
		else if (!eventDate.equals(other.eventDate))
			return false;
		if (eventCreationDate == null) {
			if (other.eventCreationDate != null)
				return false;
		}
		else if (!eventCreationDate.equals(other.eventCreationDate))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((eventId == null) ? 0 : eventId.hashCode());
		result = prime * result + ((eventTitle == null) ? 0 : eventTitle.hashCode());
		result = prime * result + ((eventDesc == null) ? 0 : eventDesc.hashCode());
		result = prime * result + ((eventLocation == null) ? 0 : eventLocation.hashCode());
		result = prime * result + ((eventOrganiser == null) ? 0 : eventOrganiser.hashCode());
		result = prime * result + ((eventExpert == null) ? 0 : eventExpert.hashCode());
		result = prime * result + ((eventEstimatedCost == null) ? 0 : eventEstimatedCost.hashCode());
		result = prime * result + ((eventDate == null) ? 0 : eventDate.hashCode());
		result = prime * result + ((eventCreationDate == null) ? 0 : eventCreationDate.hashCode());
		return result;
	}
}
