/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Individuals implements java.io.Serializable {

	private static final long serialVersionUID = -103314822;

	private java.lang.Integer  indId;
	private java.lang.String   indFname;
	private java.lang.String   indMname;
	private java.lang.String   indLname;
	private java.lang.String   indEmail;
	private java.lang.Integer  indAddress;
	private java.lang.String   indCellno;
	private java.sql.Timestamp indCreationDate;

	public Individuals() {}

	public Individuals(
		java.lang.Integer  indId,
		java.lang.String   indFname,
		java.lang.String   indMname,
		java.lang.String   indLname,
		java.lang.String   indEmail,
		java.lang.Integer  indAddress,
		java.lang.String   indCellno,
		java.sql.Timestamp indCreationDate
	) {
		this.indId = indId;
		this.indFname = indFname;
		this.indMname = indMname;
		this.indLname = indLname;
		this.indEmail = indEmail;
		this.indAddress = indAddress;
		this.indCellno = indCellno;
		this.indCreationDate = indCreationDate;
	}

	public java.lang.Integer getIndId() {
		return this.indId;
	}

	public void setIndId(java.lang.Integer indId) {
		this.indId = indId;
	}

	public java.lang.String getIndFname() {
		return this.indFname;
	}

	public void setIndFname(java.lang.String indFname) {
		this.indFname = indFname;
	}

	public java.lang.String getIndMname() {
		return this.indMname;
	}

	public void setIndMname(java.lang.String indMname) {
		this.indMname = indMname;
	}

	public java.lang.String getIndLname() {
		return this.indLname;
	}

	public void setIndLname(java.lang.String indLname) {
		this.indLname = indLname;
	}

	public java.lang.String getIndEmail() {
		return this.indEmail;
	}

	public void setIndEmail(java.lang.String indEmail) {
		this.indEmail = indEmail;
	}

	public java.lang.Integer getIndAddress() {
		return this.indAddress;
	}

	public void setIndAddress(java.lang.Integer indAddress) {
		this.indAddress = indAddress;
	}

	public java.lang.String getIndCellno() {
		return this.indCellno;
	}

	public void setIndCellno(java.lang.String indCellno) {
		this.indCellno = indCellno;
	}

	public java.sql.Timestamp getIndCreationDate() {
		return this.indCreationDate;
	}

	public void setIndCreationDate(java.sql.Timestamp indCreationDate) {
		this.indCreationDate = indCreationDate;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Individuals other = (Individuals) obj;
		if (indId == null) {
			if (other.indId != null)
				return false;
		}
		else if (!indId.equals(other.indId))
			return false;
		if (indFname == null) {
			if (other.indFname != null)
				return false;
		}
		else if (!indFname.equals(other.indFname))
			return false;
		if (indMname == null) {
			if (other.indMname != null)
				return false;
		}
		else if (!indMname.equals(other.indMname))
			return false;
		if (indLname == null) {
			if (other.indLname != null)
				return false;
		}
		else if (!indLname.equals(other.indLname))
			return false;
		if (indEmail == null) {
			if (other.indEmail != null)
				return false;
		}
		else if (!indEmail.equals(other.indEmail))
			return false;
		if (indAddress == null) {
			if (other.indAddress != null)
				return false;
		}
		else if (!indAddress.equals(other.indAddress))
			return false;
		if (indCellno == null) {
			if (other.indCellno != null)
				return false;
		}
		else if (!indCellno.equals(other.indCellno))
			return false;
		if (indCreationDate == null) {
			if (other.indCreationDate != null)
				return false;
		}
		else if (!indCreationDate.equals(other.indCreationDate))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((indId == null) ? 0 : indId.hashCode());
		result = prime * result + ((indFname == null) ? 0 : indFname.hashCode());
		result = prime * result + ((indMname == null) ? 0 : indMname.hashCode());
		result = prime * result + ((indLname == null) ? 0 : indLname.hashCode());
		result = prime * result + ((indEmail == null) ? 0 : indEmail.hashCode());
		result = prime * result + ((indAddress == null) ? 0 : indAddress.hashCode());
		result = prime * result + ((indCellno == null) ? 0 : indCellno.hashCode());
		result = prime * result + ((indCreationDate == null) ? 0 : indCreationDate.hashCode());
		return result;
	}
}
