/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Individuals implements java.io.Serializable {

	private static final long serialVersionUID = 473802156;

	private java.lang.Integer  indId;
	private java.lang.String   indFname;
	private java.lang.String   indMname;
	private java.lang.String   indLname;
	private java.lang.String   indEmail;
	private java.lang.String   indQualification;
	private java.lang.String   indAreaOfExperties;
	private java.lang.Integer  indExperinceYears;
	private java.lang.String   indAboutExperience;
	private java.lang.Integer  indCellno;
	private java.lang.String   indAddress;
	private java.lang.String   indCity;
	private java.lang.String   indState;
	private java.sql.Timestamp indCreationDate;

	public Individuals() {}

	public Individuals(
		java.lang.Integer  indId,
		java.lang.String   indFname,
		java.lang.String   indMname,
		java.lang.String   indLname,
		java.lang.String   indEmail,
		java.lang.String   indQualification,
		java.lang.String   indAreaOfExperties,
		java.lang.Integer  indExperinceYears,
		java.lang.String   indAboutExperience,
		java.lang.Integer  indCellno,
		java.lang.String   indAddress,
		java.lang.String   indCity,
		java.lang.String   indState,
		java.sql.Timestamp indCreationDate
	) {
		this.indId = indId;
		this.indFname = indFname;
		this.indMname = indMname;
		this.indLname = indLname;
		this.indEmail = indEmail;
		this.indQualification = indQualification;
		this.indAreaOfExperties = indAreaOfExperties;
		this.indExperinceYears = indExperinceYears;
		this.indAboutExperience = indAboutExperience;
		this.indCellno = indCellno;
		this.indAddress = indAddress;
		this.indCity = indCity;
		this.indState = indState;
		this.indCreationDate = indCreationDate;
	}

	public java.lang.Integer getIndId() {
		return this.indId;
	}

	public void setIndId(java.lang.Integer indId) {
		this.indId = indId;
	}

	public java.lang.String getIndFname() {
		return this.indFname;
	}

	public void setIndFname(java.lang.String indFname) {
		this.indFname = indFname;
	}

	public java.lang.String getIndMname() {
		return this.indMname;
	}

	public void setIndMname(java.lang.String indMname) {
		this.indMname = indMname;
	}

	public java.lang.String getIndLname() {
		return this.indLname;
	}

	public void setIndLname(java.lang.String indLname) {
		this.indLname = indLname;
	}

	public java.lang.String getIndEmail() {
		return this.indEmail;
	}

	public void setIndEmail(java.lang.String indEmail) {
		this.indEmail = indEmail;
	}

	public java.lang.String getIndQualification() {
		return this.indQualification;
	}

	public void setIndQualification(java.lang.String indQualification) {
		this.indQualification = indQualification;
	}

	public java.lang.String getIndAreaOfExperties() {
		return this.indAreaOfExperties;
	}

	public void setIndAreaOfExperties(java.lang.String indAreaOfExperties) {
		this.indAreaOfExperties = indAreaOfExperties;
	}

	public java.lang.Integer getIndExperinceYears() {
		return this.indExperinceYears;
	}

	public void setIndExperinceYears(java.lang.Integer indExperinceYears) {
		this.indExperinceYears = indExperinceYears;
	}

	public java.lang.String getIndAboutExperience() {
		return this.indAboutExperience;
	}

	public void setIndAboutExperience(java.lang.String indAboutExperience) {
		this.indAboutExperience = indAboutExperience;
	}

	public java.lang.Integer getIndCellno() {
		return this.indCellno;
	}

	public void setIndCellno(java.lang.Integer indCellno) {
		this.indCellno = indCellno;
	}

	public java.lang.String getIndAddress() {
		return this.indAddress;
	}

	public void setIndAddress(java.lang.String indAddress) {
		this.indAddress = indAddress;
	}

	public java.lang.String getIndCity() {
		return this.indCity;
	}

	public void setIndCity(java.lang.String indCity) {
		this.indCity = indCity;
	}

	public java.lang.String getIndState() {
		return this.indState;
	}

	public void setIndState(java.lang.String indState) {
		this.indState = indState;
	}

	public java.sql.Timestamp getIndCreationDate() {
		return this.indCreationDate;
	}

	public void setIndCreationDate(java.sql.Timestamp indCreationDate) {
		this.indCreationDate = indCreationDate;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Individuals other = (Individuals) obj;
		if (indId == null) {
			if (other.indId != null)
				return false;
		}
		else if (!indId.equals(other.indId))
			return false;
		if (indFname == null) {
			if (other.indFname != null)
				return false;
		}
		else if (!indFname.equals(other.indFname))
			return false;
		if (indMname == null) {
			if (other.indMname != null)
				return false;
		}
		else if (!indMname.equals(other.indMname))
			return false;
		if (indLname == null) {
			if (other.indLname != null)
				return false;
		}
		else if (!indLname.equals(other.indLname))
			return false;
		if (indEmail == null) {
			if (other.indEmail != null)
				return false;
		}
		else if (!indEmail.equals(other.indEmail))
			return false;
		if (indQualification == null) {
			if (other.indQualification != null)
				return false;
		}
		else if (!indQualification.equals(other.indQualification))
			return false;
		if (indAreaOfExperties == null) {
			if (other.indAreaOfExperties != null)
				return false;
		}
		else if (!indAreaOfExperties.equals(other.indAreaOfExperties))
			return false;
		if (indExperinceYears == null) {
			if (other.indExperinceYears != null)
				return false;
		}
		else if (!indExperinceYears.equals(other.indExperinceYears))
			return false;
		if (indAboutExperience == null) {
			if (other.indAboutExperience != null)
				return false;
		}
		else if (!indAboutExperience.equals(other.indAboutExperience))
			return false;
		if (indCellno == null) {
			if (other.indCellno != null)
				return false;
		}
		else if (!indCellno.equals(other.indCellno))
			return false;
		if (indAddress == null) {
			if (other.indAddress != null)
				return false;
		}
		else if (!indAddress.equals(other.indAddress))
			return false;
		if (indCity == null) {
			if (other.indCity != null)
				return false;
		}
		else if (!indCity.equals(other.indCity))
			return false;
		if (indState == null) {
			if (other.indState != null)
				return false;
		}
		else if (!indState.equals(other.indState))
			return false;
		if (indCreationDate == null) {
			if (other.indCreationDate != null)
				return false;
		}
		else if (!indCreationDate.equals(other.indCreationDate))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((indId == null) ? 0 : indId.hashCode());
		result = prime * result + ((indFname == null) ? 0 : indFname.hashCode());
		result = prime * result + ((indMname == null) ? 0 : indMname.hashCode());
		result = prime * result + ((indLname == null) ? 0 : indLname.hashCode());
		result = prime * result + ((indEmail == null) ? 0 : indEmail.hashCode());
		result = prime * result + ((indQualification == null) ? 0 : indQualification.hashCode());
		result = prime * result + ((indAreaOfExperties == null) ? 0 : indAreaOfExperties.hashCode());
		result = prime * result + ((indExperinceYears == null) ? 0 : indExperinceYears.hashCode());
		result = prime * result + ((indAboutExperience == null) ? 0 : indAboutExperience.hashCode());
		result = prime * result + ((indCellno == null) ? 0 : indCellno.hashCode());
		result = prime * result + ((indAddress == null) ? 0 : indAddress.hashCode());
		result = prime * result + ((indCity == null) ? 0 : indCity.hashCode());
		result = prime * result + ((indState == null) ? 0 : indState.hashCode());
		result = prime * result + ((indCreationDate == null) ? 0 : indCreationDate.hashCode());
		return result;
	}
}
