/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SuccessStories implements java.io.Serializable {

	private static final long serialVersionUID = 2070876638;

	private java.lang.Integer    ssId;
	private java.lang.Integer    ssEventId;
	private java.lang.String     ssDesc;
	private java.lang.String     ssVideoLink;
	private java.lang.String     ssPothosLink;
	private java.math.BigDecimal ssRating;
	private java.sql.Timestamp   ssCreationDate;

	public SuccessStories() {}

	public SuccessStories(
		java.lang.Integer    ssId,
		java.lang.Integer    ssEventId,
		java.lang.String     ssDesc,
		java.lang.String     ssVideoLink,
		java.lang.String     ssPothosLink,
		java.math.BigDecimal ssRating,
		java.sql.Timestamp   ssCreationDate
	) {
		this.ssId = ssId;
		this.ssEventId = ssEventId;
		this.ssDesc = ssDesc;
		this.ssVideoLink = ssVideoLink;
		this.ssPothosLink = ssPothosLink;
		this.ssRating = ssRating;
		this.ssCreationDate = ssCreationDate;
	}

	public java.lang.Integer getSsId() {
		return this.ssId;
	}

	public void setSsId(java.lang.Integer ssId) {
		this.ssId = ssId;
	}

	public java.lang.Integer getSsEventId() {
		return this.ssEventId;
	}

	public void setSsEventId(java.lang.Integer ssEventId) {
		this.ssEventId = ssEventId;
	}

	public java.lang.String getSsDesc() {
		return this.ssDesc;
	}

	public void setSsDesc(java.lang.String ssDesc) {
		this.ssDesc = ssDesc;
	}

	public java.lang.String getSsVideoLink() {
		return this.ssVideoLink;
	}

	public void setSsVideoLink(java.lang.String ssVideoLink) {
		this.ssVideoLink = ssVideoLink;
	}

	public java.lang.String getSsPothosLink() {
		return this.ssPothosLink;
	}

	public void setSsPothosLink(java.lang.String ssPothosLink) {
		this.ssPothosLink = ssPothosLink;
	}

	public java.math.BigDecimal getSsRating() {
		return this.ssRating;
	}

	public void setSsRating(java.math.BigDecimal ssRating) {
		this.ssRating = ssRating;
	}

	public java.sql.Timestamp getSsCreationDate() {
		return this.ssCreationDate;
	}

	public void setSsCreationDate(java.sql.Timestamp ssCreationDate) {
		this.ssCreationDate = ssCreationDate;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final SuccessStories other = (SuccessStories) obj;
		if (ssId == null) {
			if (other.ssId != null)
				return false;
		}
		else if (!ssId.equals(other.ssId))
			return false;
		if (ssEventId == null) {
			if (other.ssEventId != null)
				return false;
		}
		else if (!ssEventId.equals(other.ssEventId))
			return false;
		if (ssDesc == null) {
			if (other.ssDesc != null)
				return false;
		}
		else if (!ssDesc.equals(other.ssDesc))
			return false;
		if (ssVideoLink == null) {
			if (other.ssVideoLink != null)
				return false;
		}
		else if (!ssVideoLink.equals(other.ssVideoLink))
			return false;
		if (ssPothosLink == null) {
			if (other.ssPothosLink != null)
				return false;
		}
		else if (!ssPothosLink.equals(other.ssPothosLink))
			return false;
		if (ssRating == null) {
			if (other.ssRating != null)
				return false;
		}
		else if (!ssRating.equals(other.ssRating))
			return false;
		if (ssCreationDate == null) {
			if (other.ssCreationDate != null)
				return false;
		}
		else if (!ssCreationDate.equals(other.ssCreationDate))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ssId == null) ? 0 : ssId.hashCode());
		result = prime * result + ((ssEventId == null) ? 0 : ssEventId.hashCode());
		result = prime * result + ((ssDesc == null) ? 0 : ssDesc.hashCode());
		result = prime * result + ((ssVideoLink == null) ? 0 : ssVideoLink.hashCode());
		result = prime * result + ((ssPothosLink == null) ? 0 : ssPothosLink.hashCode());
		result = prime * result + ((ssRating == null) ? 0 : ssRating.hashCode());
		result = prime * result + ((ssCreationDate == null) ? 0 : ssCreationDate.hashCode());
		return result;
	}
}
