/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements java.io.Serializable {

	private static final long serialVersionUID = 943559754;

	private java.lang.Integer  usrId;
	private java.lang.String   usrPassword;
	private java.lang.String   usrName;
	private java.lang.Integer  usrTypId;
	private java.sql.Timestamp usrAddrCreationDate;

	public Users() {}

	public Users(
		java.lang.Integer  usrId,
		java.lang.String   usrPassword,
		java.lang.String   usrName,
		java.lang.Integer  usrTypId,
		java.sql.Timestamp usrAddrCreationDate
	) {
		this.usrId = usrId;
		this.usrPassword = usrPassword;
		this.usrName = usrName;
		this.usrTypId = usrTypId;
		this.usrAddrCreationDate = usrAddrCreationDate;
	}

	public java.lang.Integer getUsrId() {
		return this.usrId;
	}

	public void setUsrId(java.lang.Integer usrId) {
		this.usrId = usrId;
	}

	public java.lang.String getUsrPassword() {
		return this.usrPassword;
	}

	public void setUsrPassword(java.lang.String usrPassword) {
		this.usrPassword = usrPassword;
	}

	public java.lang.String getUsrName() {
		return this.usrName;
	}

	public void setUsrName(java.lang.String usrName) {
		this.usrName = usrName;
	}

	public java.lang.Integer getUsrTypId() {
		return this.usrTypId;
	}

	public void setUsrTypId(java.lang.Integer usrTypId) {
		this.usrTypId = usrTypId;
	}

	public java.sql.Timestamp getUsrAddrCreationDate() {
		return this.usrAddrCreationDate;
	}

	public void setUsrAddrCreationDate(java.sql.Timestamp usrAddrCreationDate) {
		this.usrAddrCreationDate = usrAddrCreationDate;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Users other = (Users) obj;
		if (usrId == null) {
			if (other.usrId != null)
				return false;
		}
		else if (!usrId.equals(other.usrId))
			return false;
		if (usrPassword == null) {
			if (other.usrPassword != null)
				return false;
		}
		else if (!usrPassword.equals(other.usrPassword))
			return false;
		if (usrName == null) {
			if (other.usrName != null)
				return false;
		}
		else if (!usrName.equals(other.usrName))
			return false;
		if (usrTypId == null) {
			if (other.usrTypId != null)
				return false;
		}
		else if (!usrTypId.equals(other.usrTypId))
			return false;
		if (usrAddrCreationDate == null) {
			if (other.usrAddrCreationDate != null)
				return false;
		}
		else if (!usrAddrCreationDate.equals(other.usrAddrCreationDate))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((usrId == null) ? 0 : usrId.hashCode());
		result = prime * result + ((usrPassword == null) ? 0 : usrPassword.hashCode());
		result = prime * result + ((usrName == null) ? 0 : usrName.hashCode());
		result = prime * result + ((usrTypId == null) ? 0 : usrTypId.hashCode());
		result = prime * result + ((usrAddrCreationDate == null) ? 0 : usrAddrCreationDate.hashCode());
		return result;
	}
}
