/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsRecord extends org.jooq.impl.UpdatableRecordImpl<com.webonise.proagricrowd.sql.tables.records.EventsRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1235885850;

	/**
	 * Setter for <code>proagricrowd.EVENTS.EVENT_ID</code>.
	 */
	public void setEventId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>proagricrowd.EVENTS.EVENT_ID</code>.
	 */
	public java.lang.Integer getEventId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>proagricrowd.EVENTS.EVENT_TITLE</code>.
	 */
	public void setEventTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>proagricrowd.EVENTS.EVENT_TITLE</code>.
	 */
	public java.lang.String getEventTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>proagricrowd.EVENTS.EVENT_DESC</code>.
	 */
	public void setEventDesc(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>proagricrowd.EVENTS.EVENT_DESC</code>.
	 */
	public java.lang.String getEventDesc() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>proagricrowd.EVENTS.EVENT_LOCATION</code>.
	 */
	public void setEventLocation(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>proagricrowd.EVENTS.EVENT_LOCATION</code>.
	 */
	public java.lang.String getEventLocation() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>proagricrowd.EVENTS.EVENT_ORGANISER</code>.
	 */
	public void setEventOrganiser(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>proagricrowd.EVENTS.EVENT_ORGANISER</code>.
	 */
	public java.lang.Integer getEventOrganiser() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>proagricrowd.EVENTS.EVENT_EXPERT</code>.
	 */
	public void setEventExpert(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>proagricrowd.EVENTS.EVENT_EXPERT</code>.
	 */
	public java.lang.Integer getEventExpert() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>proagricrowd.EVENTS.EVENT_ESTIMATED_COST</code>.
	 */
	public void setEventEstimatedCost(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>proagricrowd.EVENTS.EVENT_ESTIMATED_COST</code>.
	 */
	public java.lang.Integer getEventEstimatedCost() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>proagricrowd.EVENTS.EVENT_DATE</code>.
	 */
	public void setEventDate(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>proagricrowd.EVENTS.EVENT_DATE</code>.
	 */
	public java.sql.Timestamp getEventDate() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>proagricrowd.EVENTS.EVENT_CREATION_DATE</code>.
	 */
	public void setEventCreationDate(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>proagricrowd.EVENTS.EVENT_CREATION_DATE</code>.
	 */
	public java.sql.Timestamp getEventCreationDate() {
		return (java.sql.Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.webonise.proagricrowd.sql.tables.Events.EVENTS.EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.webonise.proagricrowd.sql.tables.Events.EVENTS.EVENT_TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.webonise.proagricrowd.sql.tables.Events.EVENTS.EVENT_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.webonise.proagricrowd.sql.tables.Events.EVENTS.EVENT_LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.webonise.proagricrowd.sql.tables.Events.EVENTS.EVENT_ORGANISER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.webonise.proagricrowd.sql.tables.Events.EVENTS.EVENT_EXPERT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.webonise.proagricrowd.sql.tables.Events.EVENTS.EVENT_ESTIMATED_COST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.webonise.proagricrowd.sql.tables.Events.EVENTS.EVENT_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return com.webonise.proagricrowd.sql.tables.Events.EVENTS.EVENT_CREATION_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getEventTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEventDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getEventLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getEventOrganiser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getEventExpert();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getEventEstimatedCost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getEventDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getEventCreationDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value1(java.lang.Integer value) {
		setEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value2(java.lang.String value) {
		setEventTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value3(java.lang.String value) {
		setEventDesc(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value4(java.lang.String value) {
		setEventLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value5(java.lang.Integer value) {
		setEventOrganiser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value6(java.lang.Integer value) {
		setEventExpert(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value7(java.lang.Integer value) {
		setEventEstimatedCost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value8(java.sql.Timestamp value) {
		setEventDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value9(java.sql.Timestamp value) {
		setEventCreationDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.Integer value7, java.sql.Timestamp value8, java.sql.Timestamp value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventsRecord
	 */
	public EventsRecord() {
		super(com.webonise.proagricrowd.sql.tables.Events.EVENTS);
	}

	/**
	 * Create a detached, initialised EventsRecord
	 */
	public EventsRecord(java.lang.Integer eventId, java.lang.String eventTitle, java.lang.String eventDesc, java.lang.String eventLocation, java.lang.Integer eventOrganiser, java.lang.Integer eventExpert, java.lang.Integer eventEstimatedCost, java.sql.Timestamp eventDate, java.sql.Timestamp eventCreationDate) {
		super(com.webonise.proagricrowd.sql.tables.Events.EVENTS);

		setValue(0, eventId);
		setValue(1, eventTitle);
		setValue(2, eventDesc);
		setValue(3, eventLocation);
		setValue(4, eventOrganiser);
		setValue(5, eventExpert);
		setValue(6, eventEstimatedCost);
		setValue(7, eventDate);
		setValue(8, eventCreationDate);
	}
}
