/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndividualsRecord extends org.jooq.impl.UpdatableRecordImpl<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -946104061;

	/**
	 * Setter for <code>proagricrowd.INDIVIDUALS.IND_ID</code>.
	 */
	public void setIndId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>proagricrowd.INDIVIDUALS.IND_ID</code>.
	 */
	public java.lang.Integer getIndId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>proagricrowd.INDIVIDUALS.IND_FNAME</code>.
	 */
	public void setIndFname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>proagricrowd.INDIVIDUALS.IND_FNAME</code>.
	 */
	public java.lang.String getIndFname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>proagricrowd.INDIVIDUALS.IND_MNAME</code>.
	 */
	public void setIndMname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>proagricrowd.INDIVIDUALS.IND_MNAME</code>.
	 */
	public java.lang.String getIndMname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>proagricrowd.INDIVIDUALS.IND_LNAME</code>.
	 */
	public void setIndLname(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>proagricrowd.INDIVIDUALS.IND_LNAME</code>.
	 */
	public java.lang.String getIndLname() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>proagricrowd.INDIVIDUALS.IND_EMAIL</code>.
	 */
	public void setIndEmail(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>proagricrowd.INDIVIDUALS.IND_EMAIL</code>.
	 */
	public java.lang.String getIndEmail() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>proagricrowd.INDIVIDUALS.IND_ADDRESS</code>.
	 */
	public void setIndAddress(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>proagricrowd.INDIVIDUALS.IND_ADDRESS</code>.
	 */
	public java.lang.Integer getIndAddress() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>proagricrowd.INDIVIDUALS.IND_CELLNO</code>.
	 */
	public void setIndCellno(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>proagricrowd.INDIVIDUALS.IND_CELLNO</code>.
	 */
	public java.lang.String getIndCellno() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>proagricrowd.INDIVIDUALS.IND_CREATION_DATE</code>.
	 */
	public void setIndCreationDate(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>proagricrowd.INDIVIDUALS.IND_CREATION_DATE</code>.
	 */
	public java.sql.Timestamp getIndCreationDate() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS.IND_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS.IND_FNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS.IND_MNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS.IND_LNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS.IND_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS.IND_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS.IND_CELLNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS.IND_CREATION_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIndId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getIndFname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getIndMname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getIndLname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getIndEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getIndAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getIndCellno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getIndCreationDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndividualsRecord value1(java.lang.Integer value) {
		setIndId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndividualsRecord value2(java.lang.String value) {
		setIndFname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndividualsRecord value3(java.lang.String value) {
		setIndMname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndividualsRecord value4(java.lang.String value) {
		setIndLname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndividualsRecord value5(java.lang.String value) {
		setIndEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndividualsRecord value6(java.lang.Integer value) {
		setIndAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndividualsRecord value7(java.lang.String value) {
		setIndCellno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndividualsRecord value8(java.sql.Timestamp value) {
		setIndCreationDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndividualsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Integer value6, java.lang.String value7, java.sql.Timestamp value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IndividualsRecord
	 */
	public IndividualsRecord() {
		super(com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS);
	}

	/**
	 * Create a detached, initialised IndividualsRecord
	 */
	public IndividualsRecord(java.lang.Integer indId, java.lang.String indFname, java.lang.String indMname, java.lang.String indLname, java.lang.String indEmail, java.lang.Integer indAddress, java.lang.String indCellno, java.sql.Timestamp indCreationDate) {
		super(com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS);

		setValue(0, indId);
		setValue(1, indFname);
		setValue(2, indMname);
		setValue(3, indLname);
		setValue(4, indEmail);
		setValue(5, indAddress);
		setValue(6, indCellno);
		setValue(7, indCreationDate);
	}
}
