/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersTypeRecord extends org.jooq.impl.UpdatableRecordImpl<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 562570773;

	/**
	 * Setter for <code>proagricrowd.USERS_TYPE.USR_TYP_ID</code>.
	 */
	public void setUsrTypId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>proagricrowd.USERS_TYPE.USR_TYP_ID</code>.
	 */
	public java.lang.Integer getUsrTypId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>proagricrowd.USERS_TYPE.USR_TYP_NAME</code>.
	 */
	public void setUsrTypName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>proagricrowd.USERS_TYPE.USR_TYP_NAME</code>.
	 */
	public java.lang.String getUsrTypName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>proagricrowd.USERS_TYPE.USR_TYP_DESC</code>.
	 */
	public void setUsrTypDesc(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>proagricrowd.USERS_TYPE.USR_TYP_DESC</code>.
	 */
	public java.lang.String getUsrTypDesc() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.webonise.proagricrowd.sql.tables.UsersType.USERS_TYPE.USR_TYP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.webonise.proagricrowd.sql.tables.UsersType.USERS_TYPE.USR_TYP_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.webonise.proagricrowd.sql.tables.UsersType.USERS_TYPE.USR_TYP_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUsrTypId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUsrTypName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUsrTypDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersTypeRecord value1(java.lang.Integer value) {
		setUsrTypId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersTypeRecord value2(java.lang.String value) {
		setUsrTypName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersTypeRecord value3(java.lang.String value) {
		setUsrTypDesc(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersTypeRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersTypeRecord
	 */
	public UsersTypeRecord() {
		super(com.webonise.proagricrowd.sql.tables.UsersType.USERS_TYPE);
	}

	/**
	 * Create a detached, initialised UsersTypeRecord
	 */
	public UsersTypeRecord(java.lang.Integer usrTypId, java.lang.String usrTypName, java.lang.String usrTypDesc) {
		super(com.webonise.proagricrowd.sql.tables.UsersType.USERS_TYPE);

		setValue(0, usrTypId);
		setValue(1, usrTypName);
		setValue(2, usrTypDesc);
	}
}
