/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends org.jooq.impl.UpdatableRecordImpl<com.webonise.proagricrowd.sql.tables.records.UsersRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> {

	private static final long serialVersionUID = -392209614;

	/**
	 * Setter for <code>proagricrowd.USERS.USR_ID</code>.
	 */
	public void setUsrId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>proagricrowd.USERS.USR_ID</code>.
	 */
	public java.lang.Integer getUsrId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>proagricrowd.USERS.USR_NAME</code>.
	 */
	public void setUsrName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>proagricrowd.USERS.USR_NAME</code>.
	 */
	public java.lang.String getUsrName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>proagricrowd.USERS.USR_TYP_ID</code>.
	 */
	public void setUsrTypId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>proagricrowd.USERS.USR_TYP_ID</code>.
	 */
	public java.lang.Integer getUsrTypId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>proagricrowd.USERS.USR_ADDR_ID</code>.
	 */
	public void setUsrAddrId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>proagricrowd.USERS.USR_ADDR_ID</code>.
	 */
	public java.lang.Integer getUsrAddrId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>proagricrowd.USERS.USR_EVENT_ID</code>.
	 */
	public void setUsrEventId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>proagricrowd.USERS.USR_EVENT_ID</code>.
	 */
	public java.lang.Integer getUsrEventId() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>proagricrowd.USERS.USR_ADDR_CREATION_DATE</code>.
	 */
	public void setUsrAddrCreationDate(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>proagricrowd.USERS.USR_ADDR_CREATION_DATE</code>.
	 */
	public java.sql.Timestamp getUsrAddrCreationDate() {
		return (java.sql.Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.webonise.proagricrowd.sql.tables.Users.USERS.USR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.webonise.proagricrowd.sql.tables.Users.USERS.USR_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.webonise.proagricrowd.sql.tables.Users.USERS.USR_TYP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.webonise.proagricrowd.sql.tables.Users.USERS.USR_ADDR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.webonise.proagricrowd.sql.tables.Users.USERS.USR_EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.webonise.proagricrowd.sql.tables.Users.USERS.USR_ADDR_CREATION_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUsrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUsrName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getUsrTypId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getUsrAddrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getUsrEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getUsrAddrCreationDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value1(java.lang.Integer value) {
		setUsrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value2(java.lang.String value) {
		setUsrName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value3(java.lang.Integer value) {
		setUsrTypId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value4(java.lang.Integer value) {
		setUsrAddrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value5(java.lang.Integer value) {
		setUsrEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value6(java.sql.Timestamp value) {
		setUsrAddrCreationDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, java.sql.Timestamp value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(com.webonise.proagricrowd.sql.tables.Users.USERS);
	}

	/**
	 * Create a detached, initialised UsersRecord
	 */
	public UsersRecord(java.lang.Integer usrId, java.lang.String usrName, java.lang.Integer usrTypId, java.lang.Integer usrAddrId, java.lang.Integer usrEventId, java.sql.Timestamp usrAddrCreationDate) {
		super(com.webonise.proagricrowd.sql.tables.Users.USERS);

		setValue(0, usrId);
		setValue(1, usrName);
		setValue(2, usrTypId);
		setValue(3, usrAddrId);
		setValue(4, usrEventId);
		setValue(5, usrAddrCreationDate);
	}
}
