/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Addresses extends org.jooq.impl.TableImpl<com.webonise.proagricrowd.sql.tables.records.AddressesRecord> {

	private static final long serialVersionUID = 2051236099;

	/**
	 * The reference instance of <code>proagricrowd.ADDRESSES</code>
	 */
	public static final com.webonise.proagricrowd.sql.tables.Addresses ADDRESSES = new com.webonise.proagricrowd.sql.tables.Addresses();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.webonise.proagricrowd.sql.tables.records.AddressesRecord> getRecordType() {
		return com.webonise.proagricrowd.sql.tables.records.AddressesRecord.class;
	}

	/**
	 * The column <code>proagricrowd.ADDRESSES.ADDR_ID</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.AddressesRecord, java.lang.Integer> ADDR_ID = createField("ADDR_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.ADDRESSES.ADDR_LINE1</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.AddressesRecord, java.lang.String> ADDR_LINE1 = createField("ADDR_LINE1", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.ADDRESSES.ADDR_LINE2</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.AddressesRecord, java.lang.String> ADDR_LINE2 = createField("ADDR_LINE2", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>proagricrowd.ADDRESSES.ADDR_AREA</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.AddressesRecord, java.lang.String> ADDR_AREA = createField("ADDR_AREA", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>proagricrowd.ADDRESSES.ADDR_CITY</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.AddressesRecord, java.lang.String> ADDR_CITY = createField("ADDR_CITY", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.ADDRESSES.ADDR_STATE</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.AddressesRecord, java.lang.String> ADDR_STATE = createField("ADDR_STATE", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.ADDRESSES.ADDR_COUNTRY</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.AddressesRecord, java.lang.String> ADDR_COUNTRY = createField("ADDR_COUNTRY", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.ADDRESSES.ADDR_PINCODE</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.AddressesRecord, java.lang.Integer> ADDR_PINCODE = createField("ADDR_PINCODE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.ADDRESSES.ADDR_CREATION_DATE</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.AddressesRecord, java.sql.Timestamp> ADDR_CREATION_DATE = createField("ADDR_CREATION_DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>proagricrowd.ADDRESSES</code> table reference
	 */
	public Addresses() {
		this("ADDRESSES", null);
	}

	/**
	 * Create an aliased <code>proagricrowd.ADDRESSES</code> table reference
	 */
	public Addresses(java.lang.String alias) {
		this(alias, com.webonise.proagricrowd.sql.tables.Addresses.ADDRESSES);
	}

	private Addresses(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.AddressesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Addresses(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.AddressesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.webonise.proagricrowd.sql.Proagricrowd.PROAGRICROWD, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.webonise.proagricrowd.sql.tables.records.AddressesRecord, java.lang.Integer> getIdentity() {
		return com.webonise.proagricrowd.sql.Keys.IDENTITY_ADDRESSES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.AddressesRecord> getPrimaryKey() {
		return com.webonise.proagricrowd.sql.Keys.KEY_ADDRESSES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.AddressesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.AddressesRecord>>asList(com.webonise.proagricrowd.sql.Keys.KEY_ADDRESSES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.webonise.proagricrowd.sql.tables.Addresses as(java.lang.String alias) {
		return new com.webonise.proagricrowd.sql.tables.Addresses(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.webonise.proagricrowd.sql.tables.Addresses rename(java.lang.String name) {
		return new com.webonise.proagricrowd.sql.tables.Addresses(name, null);
	}
}
