/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Databasechangelog extends org.jooq.impl.TableImpl<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord> {

	private static final long serialVersionUID = -143742910;

	/**
	 * The reference instance of <code>proagricrowd.DATABASECHANGELOG</code>
	 */
	public static final com.webonise.proagricrowd.sql.tables.Databasechangelog DATABASECHANGELOG = new com.webonise.proagricrowd.sql.tables.Databasechangelog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord> getRecordType() {
		return com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord.class;
	}

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.ID</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.AUTHOR</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> AUTHOR = createField("AUTHOR", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.FILENAME</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> FILENAME = createField("FILENAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.DATEEXECUTED</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.sql.Timestamp> DATEEXECUTED = createField("DATEEXECUTED", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.ORDEREXECUTED</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.Integer> ORDEREXECUTED = createField("ORDEREXECUTED", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.EXECTYPE</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> EXECTYPE = createField("EXECTYPE", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.MD5SUM</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> MD5SUM = createField("MD5SUM", org.jooq.impl.SQLDataType.VARCHAR.length(35), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.DESCRIPTION</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> DESCRIPTION = createField("DESCRIPTION", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.COMMENTS</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> COMMENTS = createField("COMMENTS", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.TAG</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> TAG = createField("TAG", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.LIQUIBASE</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> LIQUIBASE = createField("LIQUIBASE", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.CONTEXTS</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> CONTEXTS = createField("CONTEXTS", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOG.LABELS</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord, java.lang.String> LABELS = createField("LABELS", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>proagricrowd.DATABASECHANGELOG</code> table reference
	 */
	public Databasechangelog() {
		this("DATABASECHANGELOG", null);
	}

	/**
	 * Create an aliased <code>proagricrowd.DATABASECHANGELOG</code> table reference
	 */
	public Databasechangelog(java.lang.String alias) {
		this(alias, com.webonise.proagricrowd.sql.tables.Databasechangelog.DATABASECHANGELOG);
	}

	private Databasechangelog(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord> aliased) {
		this(alias, aliased, null);
	}

	private Databasechangelog(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.DatabasechangelogRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.webonise.proagricrowd.sql.Proagricrowd.PROAGRICROWD, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.webonise.proagricrowd.sql.tables.Databasechangelog as(java.lang.String alias) {
		return new com.webonise.proagricrowd.sql.tables.Databasechangelog(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.webonise.proagricrowd.sql.tables.Databasechangelog rename(java.lang.String name) {
		return new com.webonise.proagricrowd.sql.tables.Databasechangelog(name, null);
	}
}
