/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Databasechangeloglock extends org.jooq.impl.TableImpl<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord> {

	private static final long serialVersionUID = -1222346082;

	/**
	 * The reference instance of <code>proagricrowd.DATABASECHANGELOGLOCK</code>
	 */
	public static final com.webonise.proagricrowd.sql.tables.Databasechangeloglock DATABASECHANGELOGLOCK = new com.webonise.proagricrowd.sql.tables.Databasechangeloglock();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord> getRecordType() {
		return com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord.class;
	}

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOGLOCK.ID</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOGLOCK.LOCKED</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord, java.lang.Boolean> LOCKED = createField("LOCKED", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOGLOCK.LOCKGRANTED</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord, java.sql.Timestamp> LOCKGRANTED = createField("LOCKGRANTED", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>proagricrowd.DATABASECHANGELOGLOCK.LOCKEDBY</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord, java.lang.String> LOCKEDBY = createField("LOCKEDBY", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>proagricrowd.DATABASECHANGELOGLOCK</code> table reference
	 */
	public Databasechangeloglock() {
		this("DATABASECHANGELOGLOCK", null);
	}

	/**
	 * Create an aliased <code>proagricrowd.DATABASECHANGELOGLOCK</code> table reference
	 */
	public Databasechangeloglock(java.lang.String alias) {
		this(alias, com.webonise.proagricrowd.sql.tables.Databasechangeloglock.DATABASECHANGELOGLOCK);
	}

	private Databasechangeloglock(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord> aliased) {
		this(alias, aliased, null);
	}

	private Databasechangeloglock(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.webonise.proagricrowd.sql.Proagricrowd.PROAGRICROWD, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord> getPrimaryKey() {
		return com.webonise.proagricrowd.sql.Keys.KEY_DATABASECHANGELOGLOCK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.DatabasechangeloglockRecord>>asList(com.webonise.proagricrowd.sql.Keys.KEY_DATABASECHANGELOGLOCK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.webonise.proagricrowd.sql.tables.Databasechangeloglock as(java.lang.String alias) {
		return new com.webonise.proagricrowd.sql.tables.Databasechangeloglock(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.webonise.proagricrowd.sql.tables.Databasechangeloglock rename(java.lang.String name) {
		return new com.webonise.proagricrowd.sql.tables.Databasechangeloglock(name, null);
	}
}
