/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Individuals extends org.jooq.impl.TableImpl<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord> {

	private static final long serialVersionUID = -1956299383;

	/**
	 * The reference instance of <code>proagricrowd.INDIVIDUALS</code>
	 */
	public static final com.webonise.proagricrowd.sql.tables.Individuals INDIVIDUALS = new com.webonise.proagricrowd.sql.tables.Individuals();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord> getRecordType() {
		return com.webonise.proagricrowd.sql.tables.records.IndividualsRecord.class;
	}

	/**
	 * The column <code>proagricrowd.INDIVIDUALS.IND_ID</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, java.lang.Integer> IND_ID = createField("IND_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.INDIVIDUALS.IND_FNAME</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, java.lang.String> IND_FNAME = createField("IND_FNAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.INDIVIDUALS.IND_MNAME</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, java.lang.String> IND_MNAME = createField("IND_MNAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>proagricrowd.INDIVIDUALS.IND_LNAME</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, java.lang.String> IND_LNAME = createField("IND_LNAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.INDIVIDUALS.IND_EMAIL</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, java.lang.String> IND_EMAIL = createField("IND_EMAIL", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.INDIVIDUALS.IND_ADDRESS</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, java.lang.Integer> IND_ADDRESS = createField("IND_ADDRESS", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.INDIVIDUALS.IND_CELLNO</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, java.lang.String> IND_CELLNO = createField("IND_CELLNO", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.INDIVIDUALS.IND_CREATION_DATE</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, java.sql.Timestamp> IND_CREATION_DATE = createField("IND_CREATION_DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>proagricrowd.INDIVIDUALS</code> table reference
	 */
	public Individuals() {
		this("INDIVIDUALS", null);
	}

	/**
	 * Create an aliased <code>proagricrowd.INDIVIDUALS</code> table reference
	 */
	public Individuals(java.lang.String alias) {
		this(alias, com.webonise.proagricrowd.sql.tables.Individuals.INDIVIDUALS);
	}

	private Individuals(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Individuals(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.webonise.proagricrowd.sql.Proagricrowd.PROAGRICROWD, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, java.lang.Integer> getIdentity() {
		return com.webonise.proagricrowd.sql.Keys.IDENTITY_INDIVIDUALS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord> getPrimaryKey() {
		return com.webonise.proagricrowd.sql.Keys.KEY_INDIVIDUALS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord>>asList(com.webonise.proagricrowd.sql.Keys.KEY_INDIVIDUALS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.webonise.proagricrowd.sql.tables.records.IndividualsRecord, ?>>asList(com.webonise.proagricrowd.sql.Keys.FK_ADDRESS_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.webonise.proagricrowd.sql.tables.Individuals as(java.lang.String alias) {
		return new com.webonise.proagricrowd.sql.tables.Individuals(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.webonise.proagricrowd.sql.tables.Individuals rename(java.lang.String name) {
		return new com.webonise.proagricrowd.sql.tables.Individuals(name, null);
	}
}
