/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SuccessStories extends org.jooq.impl.TableImpl<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord> {

	private static final long serialVersionUID = 897250306;

	/**
	 * The reference instance of <code>proagricrowd.SUCCESS_STORIES</code>
	 */
	public static final com.webonise.proagricrowd.sql.tables.SuccessStories SUCCESS_STORIES = new com.webonise.proagricrowd.sql.tables.SuccessStories();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord> getRecordType() {
		return com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord.class;
	}

	/**
	 * The column <code>proagricrowd.SUCCESS_STORIES.SS_ID</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord, java.lang.Integer> SS_ID = createField("SS_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.SUCCESS_STORIES.SS_EVENT_ID</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord, java.lang.Integer> SS_EVENT_ID = createField("SS_EVENT_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.SUCCESS_STORIES.SS_DESC</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord, java.lang.String> SS_DESC = createField("SS_DESC", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>proagricrowd.SUCCESS_STORIES.SS_VIDEO_LINK</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord, java.lang.String> SS_VIDEO_LINK = createField("SS_VIDEO_LINK", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>proagricrowd.SUCCESS_STORIES.SS_POTHOS_LINK</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord, java.lang.String> SS_POTHOS_LINK = createField("SS_POTHOS_LINK", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.SUCCESS_STORIES.SS_RATING</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord, java.math.BigDecimal> SS_RATING = createField("SS_RATING", org.jooq.impl.SQLDataType.DECIMAL.precision(2, 2).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.SUCCESS_STORIES.SS_CREATION_DATE</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord, java.sql.Timestamp> SS_CREATION_DATE = createField("SS_CREATION_DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>proagricrowd.SUCCESS_STORIES</code> table reference
	 */
	public SuccessStories() {
		this("SUCCESS_STORIES", null);
	}

	/**
	 * Create an aliased <code>proagricrowd.SUCCESS_STORIES</code> table reference
	 */
	public SuccessStories(java.lang.String alias) {
		this(alias, com.webonise.proagricrowd.sql.tables.SuccessStories.SUCCESS_STORIES);
	}

	private SuccessStories(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord> aliased) {
		this(alias, aliased, null);
	}

	private SuccessStories(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.webonise.proagricrowd.sql.Proagricrowd.PROAGRICROWD, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord, java.lang.Integer> getIdentity() {
		return com.webonise.proagricrowd.sql.Keys.IDENTITY_SUCCESS_STORIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord> getPrimaryKey() {
		return com.webonise.proagricrowd.sql.Keys.KEY_SUCCESS_STORIES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord>>asList(com.webonise.proagricrowd.sql.Keys.KEY_SUCCESS_STORIES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.webonise.proagricrowd.sql.tables.records.SuccessStoriesRecord, ?>>asList(com.webonise.proagricrowd.sql.Keys.FK_EVENT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.webonise.proagricrowd.sql.tables.SuccessStories as(java.lang.String alias) {
		return new com.webonise.proagricrowd.sql.tables.SuccessStories(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.webonise.proagricrowd.sql.tables.SuccessStories rename(java.lang.String name) {
		return new com.webonise.proagricrowd.sql.tables.SuccessStories(name, null);
	}
}
