/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersType extends org.jooq.impl.TableImpl<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord> {

	private static final long serialVersionUID = 178695666;

	/**
	 * The reference instance of <code>proagricrowd.USERS_TYPE</code>
	 */
	public static final com.webonise.proagricrowd.sql.tables.UsersType USERS_TYPE = new com.webonise.proagricrowd.sql.tables.UsersType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord> getRecordType() {
		return com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord.class;
	}

	/**
	 * The column <code>proagricrowd.USERS_TYPE.USR_TYP_ID</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord, java.lang.Integer> USR_TYP_ID = createField("USR_TYP_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.USERS_TYPE.USR_TYP_NAME</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord, java.lang.String> USR_TYP_NAME = createField("USR_TYP_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.USERS_TYPE.USR_TYP_DESC</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord, java.lang.String> USR_TYP_DESC = createField("USR_TYP_DESC", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>proagricrowd.USERS_TYPE</code> table reference
	 */
	public UsersType() {
		this("USERS_TYPE", null);
	}

	/**
	 * Create an aliased <code>proagricrowd.USERS_TYPE</code> table reference
	 */
	public UsersType(java.lang.String alias) {
		this(alias, com.webonise.proagricrowd.sql.tables.UsersType.USERS_TYPE);
	}

	private UsersType(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private UsersType(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.webonise.proagricrowd.sql.Proagricrowd.PROAGRICROWD, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord, java.lang.Integer> getIdentity() {
		return com.webonise.proagricrowd.sql.Keys.IDENTITY_USERS_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord> getPrimaryKey() {
		return com.webonise.proagricrowd.sql.Keys.KEY_USERS_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.UsersTypeRecord>>asList(com.webonise.proagricrowd.sql.Keys.KEY_USERS_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.webonise.proagricrowd.sql.tables.UsersType as(java.lang.String alias) {
		return new com.webonise.proagricrowd.sql.tables.UsersType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.webonise.proagricrowd.sql.tables.UsersType rename(java.lang.String name) {
		return new com.webonise.proagricrowd.sql.tables.UsersType(name, null);
	}
}
