/**
 * This class is generated by jOOQ
 */
package com.webonise.proagricrowd.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends org.jooq.impl.TableImpl<com.webonise.proagricrowd.sql.tables.records.UsersRecord> {

	private static final long serialVersionUID = -1798856640;

	/**
	 * The reference instance of <code>proagricrowd.USERS</code>
	 */
	public static final com.webonise.proagricrowd.sql.tables.Users USERS = new com.webonise.proagricrowd.sql.tables.Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.webonise.proagricrowd.sql.tables.records.UsersRecord> getRecordType() {
		return com.webonise.proagricrowd.sql.tables.records.UsersRecord.class;
	}

	/**
	 * The column <code>proagricrowd.USERS.USR_ID</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.UsersRecord, java.lang.Integer> USR_ID = createField("USR_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.USERS.USR_PASSWORD</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.UsersRecord, java.lang.String> USR_PASSWORD = createField("USR_PASSWORD", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.USERS.USR_NAME</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.UsersRecord, java.lang.String> USR_NAME = createField("USR_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.USERS.USR_TYP_ID</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.UsersRecord, java.lang.Integer> USR_TYP_ID = createField("USR_TYP_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.USERS.USR_ADDR_ID</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.UsersRecord, java.lang.Integer> USR_ADDR_ID = createField("USR_ADDR_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>proagricrowd.USERS.USR_ADDR_CREATION_DATE</code>.
	 */
	public final org.jooq.TableField<com.webonise.proagricrowd.sql.tables.records.UsersRecord, java.sql.Timestamp> USR_ADDR_CREATION_DATE = createField("USR_ADDR_CREATION_DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>proagricrowd.USERS</code> table reference
	 */
	public Users() {
		this("USERS", null);
	}

	/**
	 * Create an aliased <code>proagricrowd.USERS</code> table reference
	 */
	public Users(java.lang.String alias) {
		this(alias, com.webonise.proagricrowd.sql.tables.Users.USERS);
	}

	private Users(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.UsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Users(java.lang.String alias, org.jooq.Table<com.webonise.proagricrowd.sql.tables.records.UsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.webonise.proagricrowd.sql.Proagricrowd.PROAGRICROWD, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.UsersRecord> getPrimaryKey() {
		return com.webonise.proagricrowd.sql.Keys.KEY_USERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.UsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.webonise.proagricrowd.sql.tables.records.UsersRecord>>asList(com.webonise.proagricrowd.sql.Keys.KEY_USERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.webonise.proagricrowd.sql.tables.records.UsersRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.webonise.proagricrowd.sql.tables.records.UsersRecord, ?>>asList(com.webonise.proagricrowd.sql.Keys.FK_USR_ID, com.webonise.proagricrowd.sql.Keys.FK_USR_TYPE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.webonise.proagricrowd.sql.tables.Users as(java.lang.String alias) {
		return new com.webonise.proagricrowd.sql.tables.Users(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.webonise.proagricrowd.sql.tables.Users rename(java.lang.String name) {
		return new com.webonise.proagricrowd.sql.tables.Users(name, null);
	}
}
