//=require "vendor/retina.js"
//=require "vendor/jquery.fancybox.pack.js"
//=require "vendor/bootstrap.min.js"
//=require "vendor/scripts.js"
//=require "vendor/jquery.flexslider-min.js"
//=require "vendor/classie.js"
//=require "vendor/jquery.waypoints.min.js"
